=== jesusrengel/jesusrengel.github.io/Actividades/unidad7/RengelJesus_ej2.dtd
<!ELEMENT Veterinaria (Cliente | Fecha_consulta | Hora_consulta | Mascota | Veterinario)+>
<!ELEMENT Cliente (nombre_cli, telefono)>
<!ATTLIST Cliente id CDATA #REQUIRED>
<!ELEMENT nombre_cli (#PCDATA)>
<!ELEMENT telefono (#PCDATA)>
<!ELEMENT Mascota (categoria, nombre, fecha_nacimiento)>
<!ATTLIST Mascota id CDATA #REQUIRED>
<!ELEMENT categoria (#PCDATA)>
<!ELEMENT nombre (#PCDATA)>
<!ELEMENT fecha_nacimiento (#PCDATA)>
<!ELEMENT Veterinario (nombre)>
<!ATTLIST Veterinario id CDATA #REQUIRED>
<!ELEMENT identificador_vet (#PCDATA)>
<!ELEMENT Fecha_consulta (#PCDATA)>
<!ELEMENT Hora_consulta (#PCDATA)>

=== jesusrengel/jesusrengel.github.io/unidad7/RengelJesus_ej2.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Veterinaria SYSTEM "RengelJesus_ej2.dtd">
<Veterinaria>
      <Cliente id="1">       
             <nombre_cli>Jesús Tienda</nombre_cli>
             <telefono>654654654</telefono>
      </Cliente>
      <Mascota id="1">
          <categoria>Perro</categoria>
          <nombre>Bolita</nombre>
          <fecha_nacimiento>05/07/2015</fecha_nacimiento>
      </Mascota>
      <Veterinario id="1">
          <nombre>María Leiva</nombre>
      </Veterinario>
      <Fecha_consulta>12/04/2022</Fecha_consulta>
      <Hora_consulta>15:50</Hora_consulta>
      
      
      <Cliente id="2">    
             <nombre_cli>María Mancad</nombre_cli>
             <telefono>654654654</telefono>
      </Cliente>
      <Mascota id="2">
          <categoria>Gato</categoria>
          <nombre>Nieve</nombre>
          <fecha_nacimiento>13/05/2018</fecha_nacimiento>
      </Mascota>
      <Veterinario id="2">
          <nombre>Álvaro Tienda</nombre>
      </Veterinario>
      <Fecha_consulta>17/02/2022</Fecha_consulta>
      <Hora_consulta>15:25</Hora_consulta>
</Veterinaria>
