=== jesusrengel/jesusrengel.github.io/Actividades/unidad7/RengelJesus_ej3.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="Veterinaria">
    <xs:complexType>
      <xs:choice maxOccurs="unbounded">
        <xs:element ref="Cliente"/>
        <xs:element name="Fecha_consulta" type="xs:date"/>
        <xs:element name="Hora_consulta" type="xs:time"/>
        <xs:element ref="Mascota"/>
        <xs:element ref="Veterinario"/>
      </xs:choice>
    </xs:complexType>
  </xs:element>
  <xs:element name="Cliente">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre_cli" type="xs:string"/>
        <xs:element name="telefono" type="xs:integer" />
      </xs:sequence>
      <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Mascota">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="categoria" type="xs:string"/>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="fecha_nacimiento" type="xs:date"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
  <xs:element name="Veterinario">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
      </xs:sequence>
      <xs:attribute name="id" type="xs:string" use="required"/>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== jesusrengel/jesusrengel.github.io/unidad7/RengelJesus_ej3.xml
<?xml version="1.0" encoding="UTF-8"?>
<Veterinaria xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
xsi:noNamespaceSchemaLocation="RengelJesus_ej3.xsd">
      <Cliente id="1">       
             <nombre_cli>Jesús Tienda</nombre_cli>
             <telefono>654654654</telefono>
      </Cliente>
      <Mascota id="1">
          <categoria>Perro</categoria>
          <nombre>Bolita</nombre>
          <fecha_nacimiento>2015-05-07</fecha_nacimiento>
      </Mascota>
      <Veterinario id="1">
          <nombre>María Leiva</nombre>
      </Veterinario>
      <Fecha_consulta>2017-05-07</Fecha_consulta>
      <Hora_consulta>15:50:00</Hora_consulta>
      
      
      <Cliente id="2">    
             <nombre_cli>María Mancad</nombre_cli>
             <telefono>654654654</telefono>
      </Cliente>
      <Mascota id="2">
          <categoria>Gato</categoria>
          <nombre>Nieve</nombre>
          <fecha_nacimiento>2018-05-07</fecha_nacimiento>
      </Mascota>
      <Veterinario id="2">
          <nombre>Álvaro Tienda</nombre>
      </Veterinario>
      <Fecha_consulta>2019-05-07</Fecha_consulta>
      <Hora_consulta>15:25:00</Hora_consulta>
</Veterinaria>
