=== jesusrengel/jesusrengel.github.io/unidad7/RengelJesus_ej5.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
  <xs:element name="gestion_turistica">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="hoteles"/>
        <xs:element ref="habitaciones"/>
        <xs:element ref="clientes"/>
        <xs:element ref="reservas"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="hoteles">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="correo_electronico" type="xs:string"/>
        <xs:element name="telefono" type="xs:string"/>
        <xs:element name="ubicacion" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="habitaciones">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="numero" type="xs:integer"/>
        <xs:element name="descripcion" type="xs:string"/>
        <xs:element name="hotel_perteneciente" type="xs:string"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="clientes">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="nombre" type="xs:string"/>
        <xs:element name="fecha_entrada" type="xs:date"/>
        <xs:element name="fecha_salida" type="xs:date"/>
        <xs:element name="importe" type="xs:decimal"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
  <xs:element name="reservas">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="fecha_entrada" type="xs:date"/>
        <xs:element name="fecha_salida" type="xs:date"/>
        <xs:element name="importe" type="xs:decimal"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== jesusrengel/jesusrengel.github.io/unidad7/RengelJesus_ej5.xml
<?xml version="1.0" encoding="UTF-8"?>
<gestion_turistica xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
 xsi:noNamespaceSchemaLocation="RengelJesus_ej5.xsd">
    <hoteles>
        <nombre>Palace</nombre>
        <correo_electronico>palace@gmail.com</correo_electronico>
        <telefono>654654654</telefono>
        <ubicacion>Madrid</ubicacion>
    </hoteles>
    <habitaciones>
        <numero>54</numero>
        <descripcion>Buena</descripcion>
        <hotel_perteneciente>Palace</hotel_perteneciente>
    </habitaciones>
    <clientes>
    <nombre>Jesus</nombre>
    <fecha_entrada>2015-10-10</fecha_entrada>
    <fecha_salida>2015-09-08</fecha_salida>
    <importe>255</importe> 
    </clientes>
    <reservas>
    <fecha_entrada>2015-10-10</fecha_entrada>
    <fecha_salida>2015-09-08</fecha_salida>
    <importe>52</importe>
    </reservas>
</gestion_turistica>
